Repository anisdzdev/CopNoDrop, pull requests merged in 2022-01, with the labels that each got.

#8 Frontend: Setup Angular and file structure
  client/.browserslistrc
  client/.editorconfig
  client/.gitignore
  client/README.md
  client/angular.json
  client/karma.conf.js
  client/package-lock.json
  client/package.json
  client/src/app/app-routing.module.ts
  client/src/app/app.component.html
  client/src/app/app.component.scss
  client/src/app/app.component.spec.ts
  client/src/app/app.component.ts
  client/src/app/app.module.ts
  client/src/app/auth/auth.component.html
  client/src/app/auth/auth.component.scss
  client/src/app/auth/auth.component.spec.ts
  client/src/app/auth/auth.component.ts
  client/src/app/checkout/checkout.component.html
  client/src/app/checkout/checkout.component.scss
  client/src/app/checkout/checkout.component.spec.ts
  client/src/app/checkout/checkout.component.ts
  client/src/app/seller/seller.component.html
  client/src/app/seller/seller.component.scss
  client/src/app/seller/seller.component.spec.ts
  client/src/app/seller/seller.component.ts
  client/src/app/shared/footer/footer.component.html
  client/src/app/shared/footer/footer.component.scss
  client/src/app/shared/footer/footer.component.spec.ts
  client/src/app/shared/footer/footer.component.ts
  client/src/app/shared/header/header.component.html
  client/src/app/shared/header/header.component.scss
  client/src/app/shared/header/header.component.spec.ts
  client/src/app/shared/header/header.component.ts
  client/src/app/shop/shop.component.html
  client/src/app/shop/shop.component.scss
  client/src/app/shop/shop.component.spec.ts
  client/src/app/shop/shop.component.ts
  client/src/app/user/user.component.html
  client/src/app/user/user.component.scss
  client/src/app/user/user.component.spec.ts
  client/src/app/user/user.component.ts
  client/src/assets/.gitkeep
  client/src/environments/environment.prod.ts
  client/src/environments/environment.ts
  client/src/favicon.ico
  client/src/index.html
  client/src/main.ts
  client/src/polyfills.ts
  client/src/styles.scss
  client/src/test.ts
  client/tsconfig.app.json
  client/tsconfig.json
  client/tsconfig.spec.json
Labels: frontend

#21 Update Readme File to include specs
  README.md
Labels: documentation

#22 setup login and sign up components in auth.
  client/src/app/app.module.ts
  client/src/app/auth/login/login.component.html
  client/src/app/auth/login/login.component.scss
  client/src/app/auth/login/login.component.spec.ts
  client/src/app/auth/login/login.component.ts
  client/src/app/auth/signup/signup.component.html
  client/src/app/auth/signup/signup.component.scss
  client/src/app/auth/signup/signup.component.spec.ts
  client/src/app/auth/signup/signup.component.ts
Labels: frontend

#24 Configuration changes
  server/app.js
  server/package.json
  server/startup/db.js
  server/startup/logging.js
Labels: bug, backend
