Repository anisdzdev/CopNoDrop, pull requests merged in 2022-02, with the labels that each got.

#28 Added PrimeNG to client folder. closes #27
  client/package-lock.json
  client/package.json
Labels: frontend

#49 Login/Sign routing
  server/controllers/users.js
  server/models/user_model.js
  server/package-lock.json
  server/package.json
  server/services/users.js
Labels: bug, documentation, backend

#61 Add cors to the express
  server/app.js
  server/controllers/orders.js
  server/controllers/products.js
  server/middleware/admin.js
  server/models/order_model.js
  server/models/product_model.js
  server/models/swaggerSchemas.js
  server/package-lock.json
  server/package.json
  server/services/orders.js
  server/services/products.js
  server/services/users.js
Labels: bug, backend, task

#65 Added delete and edit product API
  server/controllers/products.js
  server/public/products/1645069740741.png
  server/services/products.js
Labels: documentation, backend, task

#69 Setup Test dependencies
  .github/workflows/node.js.yml
  server/package-lock.json
  server/package.json
  server/tests/simple.test.js
Labels: backend

#71 Cart Component Page design merged to main
  client/package.json
  client/src/app/app-routing.module.ts
  client/src/app/app.component.scss
  client/src/app/auth/login/login.component.scss
  client/src/app/auth/signup/signup.component.scss
  client/src/app/shared/cart/cart.component.html
  client/src/app/shared/cart/cart.component.scss
  client/src/app/shared/cart/cart.component.spec.ts
  client/src/app/shared/cart/cart.component.ts
  client/src/app/shared/shared.module.ts
  client/src/app/shared/shared.service.ts
  client/src/assets/styles/_styles.scss
Labels: frontend

#77 Changed the product POST request - Product images
  server/controllers/products.js
  server/package-lock.json
  server/services/products.js
Labels: bug, backend

#80 Login/sign up modifications
  client/src/app/auth/auth.module.ts
  client/src/app/auth/login/login.component.html
  client/src/app/auth/login/login.component.scss
  client/src/app/auth/login/login.component.ts
  client/src/app/auth/signup/signup.component.html
  client/src/app/auth/signup/signup.component.scss
  client/src/app/auth/signup/signup.component.ts
  server/package-lock.json
Labels: frontend, user story, task

#81 setup product description page #55
  client/src/app/shop/product-description/product-description.component.html
  client/src/app/shop/product-description/product-description.component.scss
Labels: frontend

#83 fixed the delete product functionality
  client/libs/products/model/products.ts
  client/src/app/seller/products/products.component.html
  client/src/app/seller/products/products.component.ts
  client/src/app/seller/seller.service.ts
Labels: bug, frontend
