Repository anisdzdev/CopNoDrop, pull requests merged in 2022-03, with the labels that each got.

#100 404 Page Version1
  client/src/app/app-routing.module.ts
  client/src/app/app.module.ts
  client/src/app/pagenotfound/pagenotfound.component.html
  client/src/app/pagenotfound/pagenotfound.component.scss
  client/src/app/pagenotfound/pagenotfound.component.spec.ts
  client/src/app/pagenotfound/pagenotfound.component.ts
Labels: frontend

#101 Task - CRUD API for checkout
  server/controllers/orders.js
  server/controllers/products.js
  server/models/order_model.js
  server/models/product_model.js
  server/services/orders.js
  server/utils/results.js
Labels: documentation, backend, task

#104 User put method fix
  server/controllers/users.js
  server/services/users.js
Labels: backend

#108 Implement user testing functions
  .github/workflows/node.js.yml
  client/package-lock.json
  client/package.json
  server/controllers/users.js
  server/package-lock.json
  server/package.json
  server/services/users.js
  server/tests/simple.test.js
  server/tests/user.test.js
Labels: backend

#117 Implement user units tests
  server/tests/user.test.js
Labels: backend

#115 Adding min-height to shoplist pages and cart page to fix footer position
  client/src/app/app.component.html
  client/src/app/shared/cart/cart.component.scss
  client/src/app/shared/footer/footer.component.html
  client/src/app/shared/footer/footer.component.scss
  client/src/app/shop/product-list/product-list.component.scss
Labels: frontend

#134 Fixing package-lock.json
  client/package-lock.json
  server/package-lock.json
Labels: bug

#145 Setup Angular CI
  .github/workflows/angular.js.yml
Labels: frontend, test

#143 Update Backend Technologies
  README.md
Labels: documentation

#148 Fixing Angular CI
  .github/workflows/angular.js.yml
  client/angular.json
  client/src/app/buyer/buyer.service.ts
  client/src/app/buyer/main-page/main-page.component.spec.ts
  client/src/app/shop/product-description/product-description.component.spec.ts
  client/src/environments/environment.prod.ts
  client/src/environments/environment.ts
Labels: bug, frontend, test
