Repository anisdzdev/CopNoDrop, pull requests merged in 2022-04, with the labels that each got.

#162 Product-list footer fixing try 1
  client/src/app/shared/footer/footer.component.html
  client/src/app/shared/footer/footer.component.scss
  client/src/app/shop/product-list/product-list.component.scss
Labels: frontend

#166 Merge search bar to main
  .gitignore
  client/package-lock.json
  client/src/app/app.component.html
  client/src/app/app.module.ts
  client/src/app/home/home.component.scss
  client/src/app/shared/header/header.component.html
  client/src/app/shared/header/header.component.scss
  client/src/app/shared/header/header.component.ts
  client/src/app/shared/header/header0.component.html
  client/src/app/shared/search-bar/search-bar.component.html
  client/src/app/shared/search-bar/search-bar.component.scss
  client/src/app/shared/search-bar/search-bar.component.spec.ts
  client/src/app/shared/search-bar/search-bar.component.ts
  client/src/app/shared/shared.module.ts
  client/src/app/shared/shared.service.ts
  client/src/app/shop/product-description/product-description.component.ts
  client/src/app/shop/product-list/product-list.component.html
  client/src/app/shop/shop-routing.module.ts
  client/src/assets/logo.png
Labels: frontend

#167 Update Read.ME with coding syle
  README.md
Labels: documentation

#178 Jh/buyer2
  client/package-lock.json
  client/src/app/auth/auth.service.ts
  client/src/app/buyer/buyer.service.ts
  client/src/app/buyer/orders/orders.component.html
  client/src/app/buyer/orders/orders.component.scss
  client/src/app/buyer/orders/orders.component.ts
  client/src/app/checkout/billing/billing.component.ts
  client/src/app/home/home.component.html
  client/src/app/home/home.component.scss
  client/src/app/home/home.component.ts
  client/src/app/seller/orders/orders.component.ts
  client/src/app/seller/seller.service.ts
  client/src/app/shared/cart/cart.component.html
  client/src/app/shared/cart/cart.component.scss
  client/src/app/shared/cart/cart.component.ts
  client/src/app/shared/header/header.component.html
  client/src/app/shared/header/header.component.scss
  client/src/app/shared/header/header.component.ts
  client/src/app/shared/shared.service.ts
  client/src/app/shop/product-description/product-description.component.ts
  client/src/app/shop/product-list/product-list.component.scss
  client/src/assets/styles/_styles.scss
  client/src/favicon.ico
  server/public/products/1649391653891.PNG
Labels: frontend, test
